# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(help_text=b'Should have leading and trailing slashes.', max_length=255, verbose_name=b'URL')),
                ('title', models.CharField(max_length=128)),
                ('body', models.TextField(blank=True, max_length=65536)),
                ('section', models.CharField(blank=True, help_text=b'Enter a section name to highlight the corresponding nav element (optional).', max_length=32)),
                ('page_title', models.CharField(blank=True, max_length=512)),
                ('meta_description', models.CharField(blank=True, max_length=512)),
                ('meta_keywords', models.CharField(blank=True, max_length=512)),
                ('sitemap_changefreq', models.IntegerField(choices=[(1, b'always'), (2, b'hourly'), (3, b'daily'), (4, b'weekly'), (5, b'monthly'), (6, b'yearly'), (7, b'never')], default=3, null=True)),
                ('sitemap_priority', models.DecimalField(blank=True, decimal_places=1, default=0, help_text=b'Enter a value from 0.0 to 1.0.', max_digits=2)),
                ('template_name', models.CharField(blank=True, help_text=b"If left blank, 'pages/default.jade' will be used.", max_length=128)),
                ('visible', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('url',),
            },
        ),
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_url', models.CharField(help_text=b'Should have a leading slash.', max_length=255, verbose_name=b'Old URL')),
                ('new_url', models.CharField(help_text=b'Should have leading and trailing slashes.', max_length=255, verbose_name=b'New URL')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('old_url',),
            },
        ),
    ]
